/* AlgoCamp AI Learning Hub — concept content.
 * Concept-first: each entry explains an IDEA (not the code), with a sticky analogy
 * and an "aha" that clears a common misconception. Grounded in official docs/articles.
 */
const HUB = [
/* ───────────────────────── 01 ───────────────────────── */
{
  n:1, title:"Working with the LLM API", tag:"Chat, tokens, streaming, tool calling, JSON output",
  concepts:[
    {eyebrow:"Foundations", title:"The chat API is a stateless request/response",
     explain:"You send an array of messages — each tagged <b>system</b> (the rules), <b>user</b> (the request), or <b>assistant</b> (prior replies) — and get back generated text. The server keeps no memory between calls.",
     analogy:"A help-desk ticket: the system message is the employee handbook, the user message is the customer's question, the assistant messages are the back-and-forth so far.",
     aha:"The model doesn't 'remember' your last message — you must resend the whole conversation every single time. Memory is your job, not the API's.",
     src:"developers.openai.com/api/docs/guides/text-generation"},
    {eyebrow:"Foundations", title:"Tokens are the currency of LLMs",
     explain:"Models read and write in <b>tokens</b> — chunks of ~4 characters (≈¾ of a word). Pricing, rate limits, and context windows are all counted in tokens, not words or characters.",
     analogy:"Currency exchange: you think in words, but you're billed in tokens, and the exchange rate isn't 1:1 — a rare word or a line of code can cost several tokens.",
     aha:"Code, emoji, and non-English text burn far more tokens per character — which is why a short snippet can be surprisingly expensive.",
     src:"developers.openai.com/api/docs/introduction"},
    {eyebrow:"Steering", title:"System prompts set the personality & rules",
     explain:"The system (a.k.a. 'developer') message is processed with higher priority than user input. It defines tone, constraints, and goals before the conversation even starts.",
     analogy:"A theatre director's notes to an actor: motivation and character are set backstage, then the actor improvises within those constraints on stage.",
     aha:"System prompts don't persist across calls either — forget to resend it and the model 'forgets' who it's supposed to be.",
     src:"developers.openai.com/api/docs/guides/prompt-engineering"},
    {eyebrow:"Steering", title:"Temperature dials randomness, not intelligence",
     explain:"Temperature (≈0–2) controls how the model samples its next token. Low (0–0.3) = focused and repeatable; high (0.8+) = creative and varied. At 0 the same prompt gives near-identical output.",
     analogy:"Tuning radio static: turn it down for a clean, consistent signal; turn it up for creative noise — sometimes brilliant, sometimes nonsense.",
     aha:"Temperature changes <em>which</em> answer, not how <em>smart</em> it is. A wrong answer at 0 won't become right at 1."},
    {eyebrow:"UX", title:"Streaming reveals the answer as it's written",
     explain:"Instead of waiting for the full response, streaming sends tokens as they're generated (server-sent events). The first token often arrives in ~0.1s.",
     analogy:"Watching a game live vs. waiting for the highlight reel — same match, but you see it unfold.",
     aha:"Streaming doesn't make generation faster — total time is the same. It just slashes <em>perceived</em> latency.",
     src:"developers.openai.com/cookbook/examples/how_to_stream_completions"},
    {eyebrow:"Capabilities", title:"Tool calling: the model requests, you execute",
     explain:"You describe functions with a JSON schema; the model decides which to call and with what arguments — and returns a structured request. <b>It never runs the code.</b> Your app runs it and feeds the result back.",
     analogy:"A manager who can't touch the systems writes a request slip: 'call get_weather(Paris)'. You fetch the data and bring it back; the manager writes the final report.",
     aha:"Tool use is at least two round-trips (get the call → return the result), which is why it feels slower than plain chat.",
     src:"developers.openai.com/api/docs/guides/function-calling"},
    {eyebrow:"Capabilities", title:"Structured output guarantees valid JSON",
     explain:"With a strict schema, the API enforces that the reply matches your shape — required keys present, enums valid — at the API layer, not via hopeful prompting.",
     analogy:"A web form with required fields and dropdowns: you literally can't submit until every field is filled correctly. Plain 'please reply in JSON' is just a blank box and a promise.",
     aha:"It removes the retry-on-malformed-JSON loop entirely — the constraint is enforced, not requested.",
     src:"developers.openai.com/api/docs/guides/structured-outputs"},
    {eyebrow:"Design", title:"A provider-agnostic client interface",
     explain:"Providers (OpenAI, Anthropic, Google) have similar powers but different API shapes. Wrapping them behind one interface lets you swap models for cost, quality, or testing without rewriting your app.",
     analogy:"A universal power adapter: your laptop's plug (interface) stays the same; you just change the adapter (implementation) per country (provider).",
     aha:"The abstraction lives in <em>your</em> code — the providers will never share an API. That's exactly what makes the wrapper valuable."}
  ]
},
/* ───────────────────────── 02 ───────────────────────── */
{
  n:2, title:"Customer Support Agent", tag:"Tool-calling agent loop over FAQ, orders & tickets",
  concepts:[
    {eyebrow:"Core idea", title:"An agent <em>acts</em>; a chatbot just <em>talks</em>",
     explain:"An AI agent is an LLM that self-directs which tools to call to accomplish a task — querying databases, creating tickets, looking things up. A chatbot answers from memory inside the chat.",
     analogy:"A chatbot is a librarian answering from memory. An agent is a research assistant who walks to the shelves, pulls the records, and brings back exactly what you need.",
     aha:"The leap from 'knowing' to 'doing' is what makes agents grounded in live data instead of guessing.",
     src:"anthropic.com/research/building-effective-agents"},
    {eyebrow:"The loop", title:"ReAct: reason → act → observe → repeat",
     explain:"The agent reasons about what to do, takes one action (a tool call), observes the real result, then reasons again with that new info — looping until it can answer.",
     analogy:"A detective: form a hypothesis, check the evidence, learn from it, form a better hypothesis. They don't solve it in one shot — they iterate.",
     aha:"Remove the 'observe' step and the agent is just chaining guesses. Grounding each action in real feedback is what cuts hallucination.",
     src:"arxiv.org/abs/2210.03629"},
    {eyebrow:"Tools", title:"Tools are the agent's superpowers",
     explain:"Each tool has a name, description, and input schema (e.g. lookupOrder, searchFAQ, createTicket). The model picks one and fills the arguments; your code executes it and returns the result.",
     analogy:"A stocked pantry for a chef: they can't cook without ingredients, but given what's available they decide which to use and how to combine them.",
     aha:"The intelligence is in <em>choosing</em> the tool, not running it. Clear names and descriptions measurably improve which tool the model picks."},
    {eyebrow:"Control", title:"How it decides which tool — and when to stop",
     explain:"The model maps the user's request to tool descriptions, calls what it needs, and stops once it has enough to write a final text answer instead of another tool call.",
     analogy:"A concierge asked for weather + museum hours grabs both resources, then replies — and doesn't keep checking once they have everything.",
     aha:"It's not magic omniscience — function-calling behaviour is <em>trained</em>. Vague tool descriptions = wrong tool picked."},
    {eyebrow:"Trust", title:"Grounding turns guesses into lookups",
     explain:"Grounding means anchoring answers in retrieved real data (a live order record, an actual FAQ article) rather than the model's memory.",
     analogy:"A witness testifying from memory ('I think it was red') vs. showing a photograph ('here — it's blue').",
     aha:"Grounding converts <em>hallucinations</em> (invented facts) into <em>lookup failures</em> (tool returned nothing) — and a failed lookup is debuggable.",
     src:"claude.com/blog/tool-use-ga"},
    {eyebrow:"State", title:"Multi-turn memory is the message array",
     explain:"The API is stateless, so each turn you resend the full transcript. After every reply you append it, add the next user message, and send again.",
     analogy:"Texting someone with no short-term memory — you recap the whole thread each time. Your app just does the recap automatically.",
     aha:"Forget to append the assistant's last reply and continuity breaks — the model literally won't know what it just said.",
     src:"platform.claude.com/docs/en/api/messages"},
    {eyebrow:"Safety", title:"Guardrails & escalation to a human",
     explain:"Autonomy needs limits: cap iterations to avoid infinite loops, sandbox actions, and escalate when a request is ambiguous, high-stakes, or beyond the agent's scope.",
     analogy:"A self-driving car's safety systems: speed limits (iteration caps), geofencing (sandbox), and 'driver takeover' alerts (escalation).",
     aha:"The most <em>reliable</em> agents are semi-autonomous — chasing 100% automation usually creates more problems than it solves."}
  ]
},
/* ───────────────────────── 03 ───────────────────────── */
{
  n:3, title:"Exploring Embeddings", tag:"Vectors, cosine similarity, semantic search",
  concepts:[
    {eyebrow:"Core idea", title:"An embedding is text turned into coordinates of meaning",
     explain:"A model converts a word, sentence, or document into a vector — a list of numbers (often 384–1536 of them) that captures <em>what it means</em>, not which letters it contains.",
     analogy:"GPS for meaning: just as lat/long pinpoint a place on Earth, an embedding pinpoints a sentence in 'concept space'. Nearby points mean similar things.",
     aha:"The model doesn't 'understand' like a human — but similar meanings reliably land near each other, and that consistency is what makes them so useful.",
     src:"huggingface.co/blog/getting-started-with-embeddings"},
    {eyebrow:"Geometry", title:"Meaning lives as direction & distance",
     explain:"Position encodes meaning, and so do <em>relationships</em>. The classic: king − man + woman ≈ queen — 'royalty minus male plus female' points toward female royalty.",
     analogy:"A map drawn by climate, not geography: Miami and Singapore sit together (tropical); Moscow sits far away (cold).",
     aha:"You can't read a single dimension as 'this one means food'. Meaning emerges from the <em>whole</em> position, like a coordinate system working together.",
     src:"en.wikipedia.org/wiki/Word_embedding"},
    {eyebrow:"Math", title:"Cosine similarity measures angle, not length",
     explain:"Cosine similarity asks 'do these vectors point the same direction?' (−1 to +1), ignoring magnitude — ideal for text, where a short and a long sentence can mean the same thing.",
     analogy:"Two walkers leaving the same spot: Euclidean distance asks 'how far apart did they end up?'; cosine asks 'did they head the same way?' For meaning, direction wins.",
     aha:"When vectors are normalized to unit length, cosine similarity is just a dot product — fast, and why most libraries default to it.",
     src:"en.wikipedia.org/wiki/Cosine_similarity"},
    {eyebrow:"Application", title:"Semantic search vs keyword search",
     explain:"Keyword search matches exact words. Semantic search embeds the query and documents, then finds the nearest vectors — so 'affordable lodging' finds a page about 'cheap hotels' with zero shared words.",
     analogy:"A librarian who only shelves by exact title vs. one who's read every book and recommends by what you actually want to learn.",
     aha:"Semantic search doesn't replace keywords everywhere — for exact product codes or names, literal matching still wins."},
    {eyebrow:"Tooling", title:"Nearest neighbors & the similarity matrix",
     explain:"Finding the k closest vectors to a query powers search, recommendations, and clustering. A similarity matrix compares every item to every other, revealing clusters at a glance.",
     analogy:"A road-distance table between cities — but the 'distance' is semantic: 'Paris'↔'vacation' is close; 'Paris'↔'neural networks' is far.",
     aha:"Nearest-neighbour search surfaces <em>surprising</em> links — 'renewable energy policy' can pull up 'EV subsidies' with no keyword overlap. That serendipity is the point."},
    {eyebrow:"Tradeoffs", title:"Dimensions, and local vs API embeddings",
     explain:"More dimensions = finer distinctions, but more memory and compute. Local models (e.g. MiniLM) are free, private, offline; API models are often higher quality but cost money and send your text away.",
     analogy:"Describing colour with 1 number (brightness) is crude; add hue and saturation and you can tell red from blue. More dimensions = more nuance.",
     aha:"You can often <em>truncate</em> an embedding to fewer dimensions and it still works — how dimensions are learned matters more than their raw count.",
     src:"developers.openai.com/api/docs/guides/embeddings"}
  ]
},
/* ───────────────────────── 04 ───────────────────────── */
{
  n:4, title:"RAG over YouTube Transcripts", tag:"Chunk → embed → retrieve → grounded answer + citations",
  concepts:[
    {eyebrow:"Why", title:"RAG = give the model an open book",
     explain:"Retrieval-Augmented Generation pairs a retriever (searches a knowledge base) with a generator (the LLM). It fixes three things: stale training data, hallucination, and no access to your private docs.",
     analogy:"An open-book exam: instead of memorising every fact (and misremembering), you look up the relevant page and answer from it.",
     aha:"RAG doesn't make the model smarter — it makes it <em>better informed</em>. Same reasoning, accurate source material.",
     src:"aws.amazon.com/what-is/retrieval-augmented-generation"},
    {eyebrow:"Pipeline", title:"The six-step assembly line",
     explain:"Ingest → chunk → embed → store → retrieve → generate. Each stage is swappable: you can change chunking without touching the LLM, or upgrade embeddings without re-writing docs.",
     analogy:"Running a library: break books into chapters, index-card each one, file the cards, pull the relevant ones on a question, write a report from just those cards.",
     aha:"RAG is a <em>pipeline</em>, not a model. Most 'RAG is bad' problems are actually one weak stage — usually retrieval."},
    {eyebrow:"Prep", title:"Chunking — and why overlap matters",
     explain:"Long docs get split into ~200–1000-token pieces with a little overlap. Too big = noise and cost; too small = lost context ('Revenue grew 3%' is useless without the company and quarter).",
     analogy:"Slicing a pizza: too small and it falls apart; too big and it won't fit. The right size depends on who's eating.",
     aha:"Overlap (50–100 tokens) keeps key sentences from being cut in half at chunk boundaries — a classic silent RAG bug.",
     src:"pinecone.io/learn/chunking-strategies"},
    {eyebrow:"Retrieval", title:"Vector store & top-k search",
     explain:"Embed the question, compare it to every stored chunk by cosine similarity, and return the top-k closest (usually 3–10) ranked by score.",
     analogy:"A compass pointing 'north' (your question) among thousands of scattered compasses — you grab the ones pointing most nearly the same way.",
     aha:"This is meaning-based, not keyword-based: 'affordable housing' retrieves 'low-cost apartments' though they share no words."},
    {eyebrow:"Trust", title:"Grounding & citations beat hallucination",
     explain:"Prompt the model to answer <em>only</em> from retrieved chunks and to cite them ('[Video @ 01:23]'). It gives authoritative sources and lets users verify.",
     analogy:"Citing sources in an essay vs. writing from memory — the reader can check your work.",
     aha:"Citations don't eliminate mistakes; they make them <em>auditable</em> — you can click through and catch a misreading.",
     src:"arxiv.org/abs/2005.11401"},
    {eyebrow:"Why not just paste it all", title:"Context window & RAG vs fine-tuning",
     explain:"Even huge context windows are smaller than most knowledge bases — and stuffing everything in is costly and dilutes attention. RAG retrieves only what's relevant. Fine-tuning teaches <em>style/format</em>; RAG supplies <em>facts</em> that change often.",
     analogy:"Studying for an exam: reread every chapter the night before (stuff context) vs. review only the sections matching tonight's questions (retrieval).",
     aha:"Bigger context windows <em>help</em> RAG, not replace it — precision beats volume. And you can do both: fine-tune the voice, RAG the knowledge."}
  ]
},
/* ───────────────────────── 05 ───────────────────────── */
{
  n:5, title:"Enterprise Advanced RAG", tag:"Query expansion · BM25 + dense + RRF · reranking · filtering",
  concepts:[
    {eyebrow:"Motivation", title:"Why naive RAG breaks at scale",
     explain:"Pure semantic search suffers <b>vocabulary mismatch</b> (users say 'PTO', docs say 'paid time off'), misses exact terms (product codes, acronyms), and can't filter by department or date.",
     analogy:"A librarian who only remembers a book's 'vibe' but can't match an exact title — they hand you something that <em>feels</em> right and miss the manual on the shelf.",
     aha:"Semantic search isn't bad — it's <em>incomplete</em>. You need the librarian's intuition <em>and</em> the card catalog's precision."},
    {eyebrow:"Lexical", title:"BM25 — keyword scoring with statistics",
     explain:"BM25 scores a doc by how often query words appear, weighted so rare words count more (IDF) and long docs don't win just by length. It's pure statistics, no meaning.",
     analogy:"Searching a wiki for 'sabbatical policy': it counts exact matches, boosts the rare word 'sabbatical', and doesn't penalise short focused docs.",
     aha:"BM25 gives 'time off' and 'vacation' zero credit for being synonyms — which is exactly why you pair it with semantic search.",
     src:"en.wikipedia.org/wiki/Okapi_BM25"},
    {eyebrow:"Hybrid", title:"Run lexical + dense, then merge",
     explain:"Hybrid retrieval runs keyword (sparse) and embedding (dense) search in parallel — dense catches meaning, sparse catches exact terminology — then fuses the results.",
     analogy:"A librarian who understands concepts working alongside a card catalog with exact titles. One catches what the other misses.",
     aha:"Hybrid isn't just 'nicer' — sparse search adapts <em>instantly</em> to new jargon and product names that a dense model would need retraining to learn.",
     src:"pinecone.io/learn/hybrid-search-intro"},
    {eyebrow:"Fusion", title:"Reciprocal Rank Fusion (RRF)",
     explain:"RRF merges ranked lists by <em>position</em>, not raw score: each doc scores Σ 1/(k+rank) (k≈60). Items ranked high in <em>both</em> lists rise to the top.",
     analogy:"Two friends recommend restaurants. The place that's high on <em>both</em> their lists wins — agreement signals real relevance.",
     aha:"Dense and sparse produce incompatible scores (0.87 vs 12.3). RRF sidesteps calibration entirely by caring only about order — plug-and-play, no training.",
     src:"elastic.co/blog/improving-information-retrieval-elastic-stack-hybrid"},
    {eyebrow:"Precision", title:"Reranking with a cross-encoder",
     explain:"After retrieval returns ~50–100 candidates, a cross-encoder reads query and document <em>together</em> (not separately like the fast bi-encoder) and rescores — far more accurate, much slower.",
     analogy:"Bi-encoder: judging a résumé and a job post by separate summaries. Cross-encoder: reading them side-by-side, noticing how each requirement aligns.",
     aha:"You need both stages: fast retrieval to get from millions to ~100, then slow reranking to perfect the top 10. Cross-encoding everything would take days.",
     src:"pinecone.io/learn/series/rag/rerankers"},
    {eyebrow:"Query side", title:"Query expansion & rewriting",
     explain:"Fix the <em>question</em> before searching: add synonyms, or use HyDE — have an LLM draft a hypothetical answer, then embed <em>that</em> to find real docs that look similar.",
     analogy:"Instead of asking 'where's the PTO policy?', you hand the librarian a fake memo that <em>sounds</em> like one — they match the style and find the real thing.",
     aha:"Even if the hypothetical answer's details are wrong, the embedding's 'dense bottleneck' filters them out and keeps the topical match.",
     src:"arxiv.org/abs/2212.10496"},
    {eyebrow:"Scope", title:"Metadata filtering",
     explain:"Exact-match constraints (department=Eng, date≥2024, type=policy) narrow the search space before/after retrieval — no interpretation, just term-level matching.",
     analogy:"Walking in and saying 'only Science books published after 2020' — you delete 80% of the shelves before you even search.",
     aha:"Filters aren't a bonus — at enterprise scale they're how RAG respects org structure (right department, current policies) instead of drowning users."}
  ]
},
/* ───────────────────────── 06 ───────────────────────── */
{
  n:6, title:"Simple Neural Network", tag:"Neurons, layers, loss, gradient descent, training",
  concepts:[
    {eyebrow:"Building block", title:"A neuron = weighted sum + bias + activation",
     explain:"Each neuron multiplies its inputs by learned weights, adds a bias, then passes the result through an activation function. That's the whole atom of a neural net.",
     analogy:"A voter weighing advice: each source has a trust level (weight), you have a starting lean (bias), and a rule for when you finally 'fire' (activation).",
     aha:"A single neuron with no activation is just linear/logistic regression — it can only draw straight lines. Stacking + non-linearity is where the power comes from.",
     src:"cs231n.github.io/neural-networks-1"},
    {eyebrow:"Non-linearity", title:"Activations are 'where we get the wiggle'",
     explain:"ReLU (max(0,x)) keeps positives, zeros negatives; sigmoid squashes to (0,1). Without a non-linearity, stacking layers collapses back into one straight line.",
     analogy:"Tracing a curved mountain road with only straight sticks is impossible — activations let each layer bend the boundary to wrap around complex shapes.",
     aha:"Non-linearity isn't decoration — it's the <em>reason</em> deep networks can learn patterns no straight line ever could.",
     src:"ml-cheatsheet.readthedocs.io/en/latest/activation_functions.html"},
    {eyebrow:"Structure", title:"Layers & depth learn features hierarchically",
     explain:"A layer is many neurons in parallel; hidden layers learn intermediate features. Early layers find edges, later ones combine edges into eyes, then faces.",
     analogy:"An assembly line: each station shapes the product a bit more until the final station packages the prediction.",
     aha:"One hidden layer is a 'universal approximator' in theory but weak in practice — depth wins by capturing hierarchy <em>efficiently</em>, not by representing more."},
    {eyebrow:"Objective", title:"The loss function scores 'wrongness'",
     explain:"Loss collapses all the model's mistakes into one number. Cross-entropy, for classification, punishes confident-and-wrong answers harshly.",
     analogy:"A report card for predictions: ace it and loss → 0; say 'definitely A!' when it's B and you get a huge penalty.",
     aha:"You want low loss, not <em>zero</em> loss — zero usually means the model memorised the training set (overfitting).",
     src:"machinelearningmastery.com/loss-and-loss-functions-for-training-deep-learning-neural-networks/"},
    {eyebrow:"Learning", title:"Gradient descent = hiking downhill blindfolded",
     explain:"Repeatedly measure which way reduces loss, take a small step that way, repeat — until you reach a valley (low loss).",
     analogy:"Blindfolded on a foggy hill: feel the slope underfoot, step downhill, repeat. You can't see the bottom but you'll get there.",
     aha:"The <b>learning rate</b> is the step size: too big and you bounce over the valley; too small and training crawls.",
     src:"developers.google.com/machine-learning/crash-course"},
    {eyebrow:"Learning", title:"Backpropagation assigns blame",
     explain:"Backprop traces the error backward through the network (the chain rule, run in reverse) to compute how much each weight contributed — all gradients in one backward pass.",
     analogy:"A bucket brigade where the last person spills: you work backward asking 'how much was each person responsible?' and everyone adjusts their grip.",
     aha:"It really is 'just the chain rule' — the breakthrough was realising all those gradients are far <em>cheaper</em> to compute than people expected.",
     src:"colah.github.io/posts/2015-08-Backprop"},
    {eyebrow:"Loop", title:"Epochs, batches & why two-moons needs depth",
     explain:"An <b>epoch</b> is one full pass over the data; a <b>batch</b> is a subset processed before each weight update. The 'two-moons' dataset (interleaving crescents) isn't linearly separable — no straight line splits it.",
     analogy:"Studying flashcards: one epoch = the whole deck once; a batch = a handful before you self-test and adjust. And two interlocking rings can't be split by one straight cut.",
     aha:"That's why the demo uses two-moons: it <em>forces</em> hidden layers to learn a curved boundary — exactly what makes deep learning worth it.",
     src:"scikit-learn.org/stable/modules/generated/sklearn.datasets.make_moons.html"}
  ]
},
/* ───────────────────────── 07 ───────────────────────── */
{
  n:7, title:"Claude Code-like Coding Agent", tag:"Agentic loop + sandboxed (path-jailed) file & shell tools",
  concepts:[
    {eyebrow:"Core idea", title:"A coding agent orchestrates tools, it doesn't 'know' code",
     explain:"It's an LLM that reads/writes files and runs commands to complete dev tasks, reasoning and troubleshooting as it goes — driven by a natural-language goal like 'fix this bug'.",
     analogy:"A capable junior intern with a keyboard: give a clear task, they work in their workspace and report back — but they need boundaries.",
     aha:"The 'coding' is tool <em>orchestration</em>, not innate programming skill — the model learned to call readFile/writeFile/runCommand from examples.",
     src:"anthropic.com/news/claude-3-5-sonnet"},
    {eyebrow:"The loop", title:"Think → act → observe → repeat (ReAct)",
     explain:"The agent doesn't pre-plan everything; each action's real result decides the next step, so a failed command becomes useful information rather than a dead end.",
     analogy:"A chef tasting the soup while cooking: taste, think 'needs salt', adjust, taste again. Without tasting, you cook blind.",
     aha:"Because it adapts to results, an agent that can test → see failure → reason → retry beats any 'write perfect code in one shot' system.",
     src:"arxiv.org/abs/2210.03629"},
    {eyebrow:"Tools", title:"Files & shell are the agent's hands",
     explain:"Each tool has a schema (name, description, params). The model outputs a structured request like 'writeFile(path, contents)'; <em>your</em> app performs the actual operation.",
     analogy:"A brain with robot attachments: it can plan, but needs a gripper (writeFile) and a camera (readFile) — each with a manual (schema) — to touch the world.",
     aha:"The LLM never sees your real disk — it <em>asks</em> you to act. That gap is precisely where you install the safety boundaries."},
    {eyebrow:"Security", title:"Sandboxing & path jailing",
     explain:"Constrain the agent to a workspace and reject paths that escape it. <b>Path traversal</b> uses '../' to reach files like /etc/passwd; jailing resolves every path to absolute form and checks the prefix.",
     analogy:"A fenced playground for a puppy — free to run and dig inside, but it can't bolt into traffic or wreck the neighbour's garden.",
     aha:"String-matching '../' isn't enough — './../../secret' is sneaky. You must <em>resolve</em> the path first, then verify it's inside the jail.",
     src:"owasp.org/www-community/attacks/Path_Traversal"},
    {eyebrow:"Security", title:"Command whitelisting & timeouts",
     explain:"Allow only specific safe commands (node, ls, cat…), add timeouts and output caps. Defense in depth: even if path jailing fails, the agent still can't 'rm -rf /'.",
     analogy:"Giving a child safety scissors and washable markers instead of the whole tool cabinet — still creative, can't cause real damage.",
     aha:"Whitelisting trades raw power for safety on purpose: grant the <em>minimum</em> needed for the task, not full human access."},
    {eyebrow:"Practical", title:"Feedback, permissions & context budget",
     explain:"Agents must read command/test output to course-correct; risky actions (delete 50 files) go through human approval; and a finite context window means selectively reading only the files needed.",
     analogy:"Two-factor auth for destructive actions; and a desk too small to spread out every document — so you keep only the current task's papers in front of you.",
     aha:"More context isn't better — dumping the whole repo in <em>distracts</em> the model. Good agents read selectively, like a dev who doesn't read the entire codebase to fix one bug.",
     src:"anthropic.com/news/claude-3-5-sonnet"}
  ]
},
/* ───────────────────────── 08 ───────────────────────── */
{
  n:8, title:"AI Code Reviewer Agent", tag:"Diff parsing + deterministic linter + LLM reviewer",
  concepts:[
    {eyebrow:"Input", title:"A diff is a machine-readable list of changes",
     explain:"The unified diff format marks removed lines with <code>-</code>, added with <code>+</code>, unchanged 'context' with a space. A <b>hunk</b> (headed by <code>@@</code>) is one contiguous block of changes with its line numbers.",
     analogy:"Track Changes in a Word doc: deletions in red, additions in green, surrounding text so you know <em>where</em> the edit lives.",
     aha:"Diffs aren't just for humans — 'patch' can re-apply them to recreate exact changes elsewhere, which is how version control stores and merges edits.",
     src:"git-scm.com/docs/diff-format"},
    {eyebrow:"Determinism", title:"Linting = fast, rule-based, repeatable",
     explain:"A linter analyses code <em>without running it</em> and checks rules (use ===, no console.log, no hardcoded keys). Production linters like ESLint parse code into a syntax tree first; <em>this</em> project keeps it simple and matches regex against the raw diff lines. Same input → same output, always.",
     analogy:"Spellcheck: it flags rule violations instantly and consistently without understanding what your essay <em>means</em>.",
     aha:"Regex has no lexer, so it can't tell code from a string or comment: this project's <code>==</code> rule fires inside <code>\"a == b\"</code> and even on valid Python. That blindness is exactly why real linters build an AST.",
     src:"eslint.org/docs/latest/use/core-concepts"},
    {eyebrow:"The combo", title:"Why pair a linter with an LLM",
     explain:"Linters only catch what they're programmed to find; LLMs reason about intent, naming, missing edge cases — but are slower, non-deterministic, and can false-positive. Each covers the other's blind spot.",
     analogy:"Spellcheck catches typos; a human editor catches the unclear argument and the missing example. You want both.",
     aha:"It's defense in depth: deterministic rules for consistency and syntax, the LLM for judgment and intent."},
    {eyebrow:"Judgment", title:"The LLM reviews <em>intent</em>, not just syntax",
     explain:"Using code, names, and surrounding logic, the LLM flags things like 'this fetch can fail but has no error handling' or 'this name doesn't match what the function does'.",
     analogy:"A linter is a grammar checker; the LLM is a writing tutor asking 'what are you trying to say here?'",
     aha:"LLMs shine at the 'soft' comments — 'this could be clearer', 'consider the null case' — judgments that require understanding goals."},
    {eyebrow:"Output", title:"Structured reviews turn prose into data",
     explain:"Force a JSON schema: every comment has file, line, severity (error/warning/info), message, suggestion. Now it's sortable, filterable, and pipeable into CI.",
     analogy:"A hallway code chat vs. filed tickets — same feedback, but categorised, prioritised, and actionable.",
     aha:"Structure makes LLM output <em>composable</em>: gate a PR, generate reports, track severity trends — impossible with free text.",
     src:"developers.openai.com/api/docs/guides/structured-outputs"},
    {eyebrow:"Reality", title:"Limits: it's Copilot, not Autopilot",
     explain:"LLMs are probabilistic — the same diff can get different reviews. They hallucinate issues, miss real ones, and chaining steps compounds error (90% accuracy × 5 ≈ 59%). Latency is real too.",
     analogy:"An enthusiastic intern: fast and often insightful, but you wouldn't ship their work unreviewed.",
     aha:"The developer stays responsible — the tool <em>augments</em> judgment, it doesn't replace testing, validating, and deciding what to act on.",
     src:"honeycomb.io/blog/hard-stuff-nobody-talks-about-llm"}
  ]
},
/* ───────────────────────── 09 ───────────────────────── */
{
  n:9, title:"Voice-based AI Agent", tag:"STT → LLM → TTS pipeline; generates a real WAV",
  concepts:[
    {eyebrow:"Architecture", title:"Three stages: STT → LLM → TTS",
     explain:"Speech-to-Text writes down what was said, the LLM composes a reply, Text-to-Speech reads it aloud. Three specialised systems chained in order — each independently swappable.",
     analogy:"A relay race: STT carries the baton (audio) and hands off text; the LLM hands off a written answer; TTS carries it across the line as speech.",
     aha:"It's not one model doing everything — it's three. That's <em>why</em> voice assistants can feel slow: you wait on three processes, not one."},
    {eyebrow:"Stage 1", title:"Speech-to-Text: sound waves → words",
     explain:"Audio is digitised into ~10ms frames; frequency patterns are mapped to phonemes and words. Modern systems (e.g. Whisper) learn acoustics and language together, end-to-end.",
     analogy:"Reading lips through a fogged window — inferring discrete words from a messy, continuous signal.",
     aha:"The hard part is ambiguity: 'their/there/they're' sound identical, so STT needs language context to pick the right spelling.",
     src:"en.wikipedia.org/wiki/Speech_recognition"},
    {eyebrow:"Under the hood", title:"What a WAV file actually is",
     explain:"Analog sound is continuous; to store it you <b>sample</b> its amplitude thousands of times/sec (CD = 44,100 Hz). Each sample is a number (PCM). A WAV is just a small header + that raw list of numbers.",
     analogy:"Filming a spinning fan at 60fps: each frame samples its position; play them fast enough and motion looks smooth. Audio is the same.",
     aha:"A WAV isn't compressed magic — it's literally the waveform's height at each instant. That's why WAVs are huge but lossless.",
     src:"developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_concepts"},
    {eyebrow:"Stage 3", title:"Text-to-Speech: text → waveform",
     explain:"TTS normalises text ('Dr.'→'Doctor'), assigns pronunciations, then generates the waveform. Neural TTS predicts audio directly from text, shaping pitch, emotion, and pacing.",
     analogy:"An actor reading a script: see the words, decide how to say them, add rhythm and feeling, then perform.",
     aha:"Pronouncing words is easy; sounding <em>natural</em> is hard — 'How are you?' shifts meaning with intonation. Prosody is what early robotic voices lacked.",
     src:"en.wikipedia.org/wiki/Speech_synthesis"},
    {eyebrow:"Design", title:"Pluggable stages = swappable Lego",
     explain:"Each stage implements a simple interface (transcribe(audio)→text). Swap a mock STT for offline tests, or a better TTS voice, without touching the rest.",
     analogy:"A car's engine, transmission, and wheels — upgrade the engine without replacing the wheels.",
     aha:"Interfaces are what let you test the whole pipeline offline with instant mocks, then plug in real APIs for production."},
    {eyebrow:"Hard part", title:"Latency, turn-taking & VAD",
     explain:"Natural conversation expects sub-second replies, but three sequential stages add up — and STT can't start until you stop talking. Voice Activity Detection guesses 'are they done?', which is genuinely hard in noise.",
     analogy:"A phone call with a 3-second delay: you pause, they pause, you both talk over each other. That's the pause problem.",
     aha:"<b>Streaming</b> (start speaking the reply before the LLM finishes) doesn't make it faster — it <em>hides</em> latency by overlapping stages.",
     src:"nngroup.com/articles/response-times-3-important-limits"}
  ]
},
/* ───────────────────────── 10 ───────────────────────── */
{
  n:10, title:"AI Trading Agent", tag:"Indicators (SMA/EMA/RSI) + strategy + backtester",
  warn:"This is an educational simulation only — synthetic data, no live markets. Not financial advice.",
  concepts:[
    {eyebrow:"Foundations", title:"Indicators interpret the past, not predict the future",
     explain:"Technical indicators are math over historical price/volume that turn raw moves into readable signals — trends, momentum, possible entry/exit points.",
     analogy:"A car dashboard: speedometer, fuel gauge, temperature — each turns raw mechanical data into a signal you can act on.",
     aha:"Indicators reveal <em>what has happened</em>, not what will. They're analysis tools, not crystal balls.",
     src:"en.wikipedia.org/wiki/Technical_indicator"},
    {eyebrow:"Trend", title:"SMA smooths the noise",
     explain:"A Simple Moving Average is the plain mean of the last N prices; each day drop the oldest, add the newest. It filters short-term volatility to reveal direction.",
     analogy:"Tracking weight on a noisy scale — a 7-day average shows the real trend without daily jitter.",
     aha:"The SMA <em>lags</em> by design: a price from 20 days ago counts as much as today's, so it's slow to react. Feature and bug at once.",
     src:"en.wikipedia.org/wiki/Moving_average"},
    {eyebrow:"Trend", title:"EMA weights recent prices more",
     explain:"An Exponential Moving Average fades older prices gradually instead of dropping them abruptly, making it more responsive to recent change than the SMA.",
     analogy:"Your memory of the news: yesterday's headline is vivid, last month's a faint echo. The EMA prioritises what just happened.",
     aha:"'More responsive' ≠ 'predictive'. In choppy markets EMA sensitivity fires false signals (whipsaws) where the slower SMA stays calm."},
    {eyebrow:"Momentum", title:"RSI measures how 'stretched' price is",
     explain:"The Relative Strength Index (0–100) compares average gains to losses over ~14 days. Above 70 = overbought (pullback possible), below 30 = oversold (bounce possible).",
     analogy:"A stretched rubber band: pulled far in one direction, tension is high and it's more likely to snap back.",
     aha:"Overbought ≠ 'sell now'. In strong uptrends RSI can sit above 70 for days — it's a warning, not a trigger.",
     src:"en.wikipedia.org/wiki/Relative_strength_index"},
    {eyebrow:"Rules", title:"A strategy turns indicators into decisions",
     explain:"A strategy is systematic rules mapping signals to buy/sell/hold — e.g. buy when the fast SMA crosses above the slow SMA, sell when it crosses below. It removes emotion.",
     analogy:"A recipe: you don't improvise every time — 'when condition X, do action Y.'",
     aha:"No strategy works everywhere. Trend-following shines in trends and bleeds in sideways chop — match the strategy to the regime."},
    {eyebrow:"Validation", title:"Backtesting is rehearsal, not prophecy",
     explain:"Run the strategy over historical data with simulated capital and track return, win rate, and drawdown — a reality check before risking anything.",
     analogy:"Rehearsing a play before opening night: catch problems on stage in practice, not in front of an audience.",
     aha:"It's <em>retrodiction</em>: you're scoring data you already know. 'Worked historically' can just mean 'got lucky' or 'overfit'.",
     src:"en.wikipedia.org/wiki/Backtesting"},
    {eyebrow:"Pitfalls", title:"Overfitting & look-ahead bias",
     explain:"<b>Overfitting</b>: tuning so tightly to history that you fit noise. <b>Look-ahead bias</b>: using info you wouldn't have had in real time (e.g. trading at a close price you only knew after close).",
     analogy:"Overfitting = memorising last year's exact exam questions. Look-ahead bias = claiming you'd win poker because you saw the cards <em>after</em> the hand.",
     aha:"More parameters ≠ better. Simpler strategies are often more robust because they capture broad truths, not historical accidents."}
  ]
},
/* ───────────────────────── 11 ───────────────────────── */
{
  n:11, title:"Multi-Input OCR Model", tag:"Image branch + aux-feature branch → fused head",
  concepts:[
    {eyebrow:"Task", title:"OCR turns pixels of text into characters",
     explain:"OCR converts images of text — scans, signs, handwriting — into editable, searchable characters, mapping visual patterns to discrete symbols despite font and quality variation.",
     analogy:"Reading Grandma's cursive recipe: you decode letters from shape <em>and</em> context and expected words. OCR does both.",
     aha:"OCR isn't perfect — even clean print is 81–99% accurate, and cursive is hard because a character alone often lacks enough information without context.",
     src:"en.wikipedia.org/wiki/Optical_character_recognition"},
    {eyebrow:"Why CNNs", title:"Images have spatial structure; tables don't",
     explain:"Neighbouring pixels form meaningful patterns (edges, textures); shuffle them and meaning dies. Spreadsheet columns are independent — shuffle rows and nothing changes. Hence convolutions for images, dense layers for features.",
     analogy:"A book's meaning comes from word order; a box of alphabet magnets has no inherent order.",
     aha:"Connecting every pixel to every neuron is wasteful on big images — a 200×200 colour photo needs 120,000 weights per neuron, so real OCR reaches for CNNs that reuse one edge detector everywhere. On a tiny 14×14 digit the waste is small, which is exactly why <em>this</em> project skips convolutions and just flattens the image into a dense branch — spending its teaching budget on the fusion step instead.",
     src:"cs231n.github.io/convolutional-networks"},
    {eyebrow:"Architecture", title:"Two branches, one brain",
     explain:"A multi-input model sends each input through its own pipeline — an image branch and a dense branch for tabular features — then merges them deeper for the final decision. (Real OCR would put convolutions in the image branch; this project flattens the tiny 14×14 digit into a dense layer to keep the focus on the fusion, not the CNN.)",
     analogy:"A doctor diagnosing pneumonia uses the X-ray (visual) <em>and</em> the chart (age, symptoms, temperature) — each in its own 'language'.",
     aha:"You <em>could</em> mash everything into one vector at the start — but then pixels and feature values get treated identically, throwing away spatial structure."},
    {eyebrow:"Fusion", title:"Concatenation merges the branches",
     explain:"Concatenation stacks the branches' learned representations side by side (64 image features + 32 aux = 96), then shared 'head' layers learn which combination predicts the answer.",
     analogy:"Two friends describe a movie — one the visuals, one the plot. Combined, the description is richer than either alone.",
     aha:"It's just 'put the vectors next to each other' — but <em>after</em> each branch has extracted meaning, so the head learns 'curve + high aspect ratio = digit 3'."},
    {eyebrow:"Why fuse", title:"Modalities carry complementary info",
     explain:"Each input supplies what the other lacks: the image shows visual patterns; aux features capture measurements (aspect ratio, density) that are hard to read off raw pixels.",
     analogy:"Identifying a bird from a photo (colour, size) <em>and</em> its song (species that look identical) — neither alone is decisive.",
     aha:"Aux features aren't <em>better</em> than the image — they're <em>different</em>. But prove it before you claim it: on this toy dataset an ablation shows each input already scores ~100% alone, so fusion adds nothing here. A headline accuracy means nothing without baselines; fusion earns its keep only when the inputs are genuinely complementary (medical scan + labs, camera + LiDAR)."},
    {eyebrow:"Framework", title:"Functional API for branching graphs",
     explain:"The Sequential API stacks layers in one line — fine for a single path. Branching/merging needs the Functional API, where models are graphs and you explicitly wire outputs to inputs.",
     analogy:"Sequential = one assembly line. Functional = a factory floor where several lines converge at a final inspection station.",
     aha:"Functional isn't 'more advanced' — it's the right tool when the architecture isn't a straight line. It also validates shapes at build time, like a compiler.",
     src:"tensorflow.org/guide/keras/functional"}
  ]
},
/* ───────────────────────── 12 ───────────────────────── */
{
  n:12, title:"MNIST Autoencoder", tag:"Encoder → bottleneck → decoder; latent space",
  concepts:[
    {eyebrow:"Dataset", title:"MNIST: the 'Hello World' of vision",
     explain:"Real MNIST is 70,000 handwritten digits (0–9), 28×28 grayscale — the standard first computer-vision project. To stay fully offline this project doesn't download it: <code>data.ts</code> <em>draws</em> 400 synthetic 28×28 digits of just three classes (0, 1, 2) with seeded randomness, a stand-in that keeps the same shape without a dependency.",
     analogy:"Learning to cook with scrambled eggs: simple, forgiving, teaches fundamentals fast — you just wouldn't serve it at a Michelin restaurant.",
     aha:"MNIST is easy because it's tiny (784 pixels), not because digits are trivial — it lets you focus on the algorithm, not hours of training. And a synthetic stand-in is a fair swap here: the autoencoder lesson is about the squeeze, not about recognising real handwriting."},
    {eyebrow:"Core idea", title:"An autoencoder learns to copy itself",
     explain:"It compresses an input to a tiny form, then reconstructs the original — trained simply to make output match input. No labels, no categories.",
     analogy:"Summarise a 500-page book in 10 sentences, then rewrite the whole book from only that summary — the squeeze forces you to keep what matters.",
     aha:"It's not zip-style lossless compression — it <em>learns</em> which features matter for <em>this</em> data and discards the rest.",
     src:"en.wikipedia.org/wiki/Autoencoder"},
    {eyebrow:"Structure", title:"Encoder → bottleneck → decoder",
     explain:"The encoder shrinks the input (784→128→64→32), the bottleneck is the tiny middle (e.g. 32 numbers), and the decoder mirrors it back up (32→…→784).",
     analogy:"A funnel into a straw into a funnel — everything must squeeze through the narrow straw.",
     aha:"The bottleneck isn't a limitation — it's the whole point. Without it the network could just copy inputs unchanged and learn nothing."},
    {eyebrow:"The squeeze", title:"The latent space holds the 'essence'",
     explain:"The bottleneck stores a latent representation — abstract features the network <em>invented</em> (roundness, loopiness) to describe a digit in just 32 numbers instead of 784.",
     analogy:"A recipe doesn't list molecules — it says 'chocolate, moist, three layers'. The latent space is those compact descriptive features.",
     aha:"32 vs 784 is ~96% compression, yet it rebuilds a recognisable digit — the network discovered which 96% was redundant.",
     src:"jeremyjordan.me/autoencoders"},
    {eyebrow:"Training", title:"Reconstruction loss is a self-made teacher",
     explain:"Loss measures how different the output is from the input (e.g. MSE). Minimising it drives better reconstructions — no human labels needed; the input <em>is</em> the answer.",
     analogy:"The game of telephone: reconstruction loss counts how many words got garbled, and the network practises until almost nothing is lost.",
     aha:"This is <b>self-supervised</b> learning — huge when labels are scarce: train on a million unlabeled scans to learn features, then reuse them.",
     src:"blog.keras.io/building-autoencoders-in-keras.html"},
    {eyebrow:"Context", title:"Autoencoder vs PCA — and real uses",
     explain:"PCA finds a flat (linear) lower-dimensional surface; autoencoders with non-linear activations learn curved compressions. Uses: denoising, anomaly detection, compression.",
     analogy:"PCA flattens Earth onto a flat map (distortion); an autoencoder is a flexible sheet that hugs the actual terrain.",
     aha:"Anomaly detection falls out for free: train on normal data, and anything that reconstructs <em>badly</em> (high error) is an outlier — because the net never learned it."}
  ]
}
];
